[package]
name = "rustc-formality"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.rust-analyzer]
rustc_private=true

[dev-dependencies]
pretty_assertions = "1.3.0"

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }

[workspace]
members = [
    "crates/formality-macros",
    "crates/formality-core",
    "crates/formality-types",
    "crates/formality-logic",
    "crates/formality-decl",
    "crates/formality-body",
    "crates/formality-infer",
    "crates/formality-check",
    "crates/formality-rust",
]