[package]
name = "formality-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
formality-types = { path = "../formality-types" }
formality-macros = { path = "../formality-macros" }
formality-core = { path = "../formality-core" }
formality-logic = { path = "../formality-logic" }
formality-infer = { path = "../formality-infer" }
formality-decl = { path = "../formality-decl" }
tracing = "0.1"
formality-check = { version = "0.1.0", path = "../formality-check" }

[dev-dependencies]
expect-test = "1.4.0"
