[book]
authors = ["Niko Matsakis"]
language = "en"
multilingual = false
src = "src"
title = "A MIR Formality"
[book]
author = ["alexander Petree"]
languages = "en"
multilingual = true 
src = "src" 
title = " Rust 4 a day"
