name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  racket-test-logic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Racket
        run: |
          sudo add-apt-repository ppa:plt/racket
          sudo apt install xvfb racket
          sh -c ./revert-redex-changes
      - name: Run Tests
        run: |
          xvfb-run ./test racket-src/logic racket-src/util.rkt
  racket-test-ty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Racket
        run: |
          sudo add-apt-repository ppa:plt/racket
          sudo apt install xvfb racket
          sh -c ./revert-redex-changes
      - name: Run Tests
        run: |
          xvfb-run ./test racket-src/ty
  racket-test-decl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Racket
        run: |
          sudo add-apt-repository ppa:plt/racket
          sudo apt install xvfb racket
          sh -c ./revert-redex-changes
      - name: Run Tests
        run: |
          xvfb-run ./test racket-src/decl
  racket-test-body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Racket
        run: |
          sudo add-apt-repository ppa:plt/racket
          sudo apt install xvfb racket
          sh -c ./revert-redex-changes
      - name: Run Tests
        run: |
          xvfb-run ./test racket-src/body
  racket-test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Racket
        run: |
          sudo add-apt-repository ppa:plt/racket
          sudo apt install xvfb racket
          sh -c ./revert-redex-changes
      - name: Run Tests
        run: |
          xvfb-run ./test racket-src/check
  racket-test-rust-a-to-g:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Racket
        run: |
          sudo add-apt-repository ppa:plt/racket
          sudo apt install xvfb racket
          sh -c ./revert-redex-changes
      - name: Run Tests
        run: |
          rm -rf racket-src/rust/test/{h*,i*,j*,k*,l*,m*,n*,o*,p*,q*}
          rm -rf racket-src/rust/test/{r*,s*,t*,u*,v*,w*,x*,y*,z*}
          xvfb-run ./test racket-src/rust
  racket-test-rust-h-to-q:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Racket
        run: |
          sudo add-apt-repository ppa:plt/racket
          sudo apt install xvfb racket
          sh -c ./revert-redex-changes
      - name: Run Tests
        run: |
          rm -rf racket-src/rust/test/{a*,b*,c*,d*,e*,f*,g*}
          rm -rf racket-src/rust/test/{r*,s*,t*,u*,v*,w*,x*,y*,z*}
          xvfb-run ./test racket-src/rust
  racket-test-rust-r-to-z:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Racket
        run: |
          sudo add-apt-repository ppa:plt/racket
          sudo apt install xvfb racket
          sh -c ./revert-redex-changes
      - name: Run Tests
        run: |
          rm -rf racket-src/rust/test/{a*,b*,c*,d*,e*,f*,g*}
          rm -rf racket-src/rust/test/{h*,i*,j*,k*,l*,m*,n*,o*,p*,q*}
          xvfb-run ./test racket-src/rust
  rust-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Racket
        run: |
          sudo add-apt-repository ppa:plt/racket
          sudo apt install xvfb racket
          sh -c ./revert-redex-changes
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test